# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# to reset password: htpasswd -s -b -n internal changeme
openshift_prometheus_htpasswd_auth: internal:{SHA}+pvrmeQCmtWmYVOZ57uuITVghrM=
openshift_prometheus_basic_auth_pass: changeme
extra_prometheus_hosts:

# Uncomment this if your cluster serves privately signed certificates
# custom_ca: true

deployment:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: pelorus
    app.kubernetes.io/version: v0.33.0

exporters:
  instances:
    # Values file for exporter helm chart
  - app_name: deploytime-exporter
    source_context_dir: exporters/
    extraEnv:
    - name: APP_FILE
      value: deploytime/app.py
    source_url: https://github.com/konveyor/pelorus.git

snapshot_schedule: "@monthly"


# Specify images and their versions
# override for airgap possiblities.
images:
  grafana: image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/oauth-proxy:v4.4
  prometheus-proxy: image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/oauth-proxy:v4.4
  thanos: quay.io/thanos/thanos:v0.8.1
  thanos-proxy: registry.redhat.io/openshift3/oauth-proxy:v3.11
  web-terminal-tooling: quay.io/wto/web-terminal-tooling:1.2
